[package]
name = "simple-savvy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
savvy = { git = "https://github.com/yutannihilation/savvy", branch = "webr" }
savvy-ffi = { git = "https://github.com/yutannihilation/savvy" }

[workspace]
