# Based on https://github.com/r-wasm/actions/blob/main/.github/workflows/deploy-cran-repo.yml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Deploy CRAN repo

jobs:
  deploy-cran-repo:
    runs-on: ubuntu-latest

    concurrency:
      group: github-pages
      cancel-in-progress: true


    permissions:
      repository-projects: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v4

      - name: Build wasm packages
        uses: yutannihilation/r-wasm-actions/build-rwasm@rust
        with:
            packages: "."

      - name: Remove src
        run: rm -r _site/src/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
